# basic
title: Carter's Blog
subtitle: Think Different
favicon: https://cl.ly/073Y3j470U2X/favicon.png

# avatar: images/avatar.png
# banner_small: images/banner-small.png
# banner_large: images/banner-large.png
logo: https://cl.ly/2r000P311v3X/C.png
# disqus
#disqus_shortname: drakeleung

highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# nav #
nav:
  Home: .
  Archive: archives
  Links: /links
  Log: /log
  About: /about
  RSS: atom.xml
  # about: about
  # rss: atom.xml

# hexo-renderer-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Default post title
default_post_title: Untitled

# social
social:
  github: https://github.com/CarterJimmy
  flickr: https://www.flickr.com/photos/146675969@N03/
  telegram: https://t.me/carterjimmy/

  # weibo: http://weibo.com/10010800
  # mail: mailto:gallenhu@foxmail.com
  # twitter: https://twitter.com/GallenHu


#local_search
#定义搜索
search:
  path: search.xml
  field: post


# RSS FeedSetting
rss: /atom.xml

# Local search
local_search:
  enable: true

# 评论
disqus_shortname: carters-blog



# widget
#   title: 标题
#   content: 内容
widget:
  title: About
  content: <div><a align="center">专注记录技术与生活</a></div>

footer: Powered by <a href="https://hexo.io/" target="_blank">Hexo</a> with Theme <a href="https://github.com/GallenHu/hexo-theme-Daily" target="_blank">Daily</a>
